Hermanos:
  groupname: Hermanos
  readableName: hermanos
  description: 'hermanos que puedan ver el portal'
  icon: users
  access:
    site:
      login: 'true'
      pagina: 'true'
    admin: {  }
    admin-addon-user-manager: {  }
